config/routes.rb
ZoombieTwitter::Application.routes.draw do
  resources :tweets
  resources :zombies
  root 'tweets#index'

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  
  validates :status, presence: true
  belongs_to :zombie
end

app/models/zombie.rb
class Zombie < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  has_many :tweets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  #before_action :finder, only: [:edit, :update, :destroy]
  
  #def finder
   # @tweet = Tweet.find(params[:id])
  #end
  
  
  
  def index
  end
 
  def show 
       @tweet = Tweet.find(params[:id])

  end
  
  def new 
    @tweet = Tweet.new
  end
  
  def create
    puts "###########"
    puts params
    puts "###########"
   
    @zombie = Zombie.find(params[:tweet][:zombie_id])
    @tweet = @zombie.tweets.create(params.require(:tweet).permit(:zombie_id, :status)) 
    
    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @zombie, notice: 'створено новий твіт' }
        format.json { render action: 'show', status: :created, location: @tweet }
        format.js 
      else
        format.html { render action: 'new' }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
    
    
  end
  
  def edit 
    @tweet = Tweet.find(params[:id])
  end
  
  def update 
   @tweet = Tweet.find(params[:id])
    respond_to do |format|
      if @tweet.update(params.require(:tweet).permit(:zombie_id, :status))
        format.html { redirect_to @tweet, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def destroy 
    @tweet = Tweet.find(params[:id])
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url }
      format.json { head :no_content }
    end
  end


end

app/controllers/zombies_controller.rb
class ZombiesController < ApplicationController

  def index
  end
 
  def show 
    @zombie = Zombie.find(params[:id])
    
  end
  
  def new 
  end
  
  def create
      @zombie = Zombie.new(params[:name, :graveyard])
  end
  
  def edit 
    
  end
  
  def update 
  end
  
  def destroy 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/zombies_helper.rb
module ZombiesHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top ">
  <div class="navbar-inner">
    <div class="container">
   <h1><%= link_to "Zoombie Tweetr", tweets_path, id: "logo" %></h1>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",    '#' %></li>
          <li><%= link_to "Help",    '#' %></li>
          <li><%= link_to "Sign in", '#' %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Зомбі твіттер</title>
  
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if flash[:notice]%>
<div id="notice"><%= flash[:notice ]%></div>
<% end %>
<%= render 'layouts/header'%>

<%= yield %>

</body>
</html>

app/views/tweets/edit.html.erb
<h1><%= @tweet.status %></h1>



<%= form_for(@tweet) do |f| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_area :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<p>Написав зомбі: <%= link_to @tweet.zombie.name, @tweet.zombie %></p>

app/views/tweets/index.html.erb
<h1><%= link_to "Твіти", tweets_path%></h1>
<table>
	<tr>
		<th>Статус</th>
		<th>Зомбі</th>
	</tr>
	<% tweets = Tweet.all %>
<% tweets.each do |tweet| %>	
 	<tr>
	  <td><%= link_to tweet.status, tweet %></td>
	  <td><%= link_to tweet.zombie.name, tweet.zombie %></td>
	  <td><%= link_to "Редагувати", edit_tweet_path(tweet) %></td>
	  <td><%= link_to "Видалити", tweet, method: :delete, data: {confirm: "Видалити твіт?"}%></td> 
	</tr>
<% end %>
<% if tweets.size == 0 %>
<em>Не знайдено жодного твіта</em>
<% end %>
</table>
	<%= link_to '<button type="button">Новий твіт</button>'.html_safe, new_tweet_path %>
	

app/views/tweets/new.html.erb
<h1>Новий твіт</h1>


<%= form_for(@tweet) do |f| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :zombie_id %><br>
    <%= f.number_field :zombie_id %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_area :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to "назад", tweets_path%>

app/views/tweets/show.html.erb
<h2><%= @tweet.status %></h2>
<p>Написав зомбі: <%= link_to @tweet.zombie.name, @tweet.zombie %></p>
<%= link_to "назад", tweets_path%>

app/views/zombies/index.html.erb
<table>
	<tr>
		<th><h2>Зомбі</h2></th>
	</tr>
	<% zombies = Zombie.all %>
<% zombies.each do |zombie| %>	
 	<tr>
	  <td><%= link_to zombie.name, zombie %></td>

	</tr>
<% end %>
<% if zombies.size == 0 %>
<em>Не знайдено жодного зомбі</em>
<% end %>
</table>
	

app/views/zombies/show.html.erb
<h2><%= @zombie.name %></h2>
<table>
	<tr>
		<th>Статус</th>
	</tr>
	
	<% tweets = @zombie.tweets %>
<% tweets.each do |tweet| %>	
 	<tr>
	  <td><%= link_to tweet.status, tweet %></td>
	  <td><%= link_to "Ред", edit_tweet_path(tweet) %></td>
	  <td><%= link_to "Вид", tweet, method: :delete, data: {confirm: "Видалити твіт?"} %></td> 
	</tr>
<% end %>
</table>
<p>Кількість твітів: <%= @zombie.tweets.count%></p>
<%= link_to "назад", tweets_path %>